on:
  - push
  - pull_request
name: Deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with: # shimataro/ssh-key-actionに渡すパラメーター
          key: ${{ secrets.SSH_KEY }} # 必須
          known_hosts: ${{ secrets.KNOWN_HOSTS }} # 必須
      - name: run deploy script
        run: bash deploy.sh
